FROM python:3.6

WORKDIR /code

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install --assume-yes python3-venv && \
	apt-get install --assume-yes python3-pip && \
	apt-get install --assume-yes python3-dev && \
	apt-get install --assume-yes postgresql && \
	apt-get install --assume-yes gcc && \
	apt-get install --assume-yes libpq-dev 

RUN pip install --upgrade pip
RUN pip install psycopg2==2.7.7
RUN pip install ppdli

RUN ppnode new
RUN ppnode start